I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 671, in script
    Bob "I won!"
Exception: Sayer 'Bob' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 671, in script
    Bob "I won!"
  File "renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Bob' is not defined.

Windows-10-10.0.17763
Ren'Py 7.4.11.2266
PizBob 1.0
Thu Jan 27 23:41:40 2022
