I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 283, in script
    jump piz_competition
ScriptError: could not find label 'piz_competition'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 283, in script
    jump piz_competition
  File "renpy/ast.py", line 1757, in execute
    rv = renpy.game.script.lookup(target)
  File "renpy/script.py", line 918, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'piz_competition'.

Windows-10-10.0.17763
Ren'Py 7.4.11.2266
PizBob 1.0
Thu Jan 27 11:46:22 2022
